### ISSUE TITLE
translate description metadata

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/clariah-at-website#10]
currently we provide metadata for web-crawlers only in english.

we should translate this description: https://github.com/acdh-oeaw/clariah-at-website/blob/main/content/de/metadata/index.json

can also be done via cms: https://clariah.at/keystatic/branch/main/singleton/de_metadata

**Comment by PixlTracer** [comment]
hi, thanks for pointing this out!

i've checked  https://clariah.at/keystatic/branch/main/singleton/de_metadata which is not accessible:
<img width="925" alt="Bildschirmfoto 2024-11-04 um 11 11 27" src="https://github.com/user-attachments/assets/8f13d8fa-b6ed-40aa-bce1-0351786f5bfb">

instead I did the changes via https://clariah.at/keystatic/branch/main/singleton/de%3Aindex-page:
<img width="1411" alt="Bildschirmfoto 2024-11-04 um 11 11 53" src="https://github.com/user-attachments/assets/ad503124-34b9-44b6-b81c-5d5b36e1bbf3">

and translated the bits to:
<img width="1243" alt="Bildschirmfoto 2024-11-04 um 11 15 00" src="https://github.com/user-attachments/assets/ea28ef7e-7d1b-4a7c-9536-9f48b674d28f">

in case this is okay for everyone involved, you may close this issue now; let me know in case there is a need for a follow-up-action

**Comment by stefanprobst** [comment]
cool thanks!
