### ISSUE TITLE
font edits in keystatic do not work anymore (since update)

### ISSUE THREAD

**Issue by PixlTracer** [acdh-oeaw/clariah-at-website#12]
hi @stefanprobst 
I saw you implemented a major update these days!
unfortunately, some elements in keystatic do not work anymore:
first I noticed that the font edits are not clickable anymore; then, when looking up an old event item in EN (lecture 10.1) I received the following error:

<img width="796" alt="Bildschirmfoto 2024-11-04 um 12 57 15" src="https://github.com/user-attachments/assets/1f070645-21fb-4755-b4a5-f6dc37a29b43">

together with @ctot-nondef I had a look into the commit history (#11), and it showed that the problem might be related to the (new) libs?
<img width="755" alt="Bildschirmfoto 2024-11-04 um 13 11 19" src="https://github.com/user-attachments/assets/c08e9abc-a307-4323-9094-8620f8e20220">

I'd be in need of a rather quick fix in order to be able to do website curation and editing, thanks!

**Comment by stefanprobst** [comment]
fixed by https://github.com/acdh-oeaw/clariah-at-website/commit/b1b3a9c86593c2e051b2128d4091aea87a15bc38
